**Purpose:** To follow along chapter 10 (Eigenanalysis) of the book on Applied Multivariate Statistics in R\
**Link to the chapter:** [Click here](https://uw.pressbooks.pub/appliedmultivariatestatistics/chapter/eigenanalysis/)\
**Date:** 24/03/2026

# 1. Spectral decomposition

In [1]:
mat <- matrix(data = c(3, 6,
                       2, 5),
              nrow = 2)
E <- eigen(x = mat)
E

eigen() decomposition
$values
[1] 7.6055513 0.3944487

$vectors
           [,1]       [,2]
[1,] -0.3983218 -0.6088937
[2,] -0.9172457  0.7932518

In [2]:
evalues <- E$values # eigen value
evectors <- E$vectors # eigen vector

In [3]:
# Verify multiplication for the first eigvalue-eigenvector pair
# matrix x eigenvector = eigenvalue x eigenvector
cat("Matrix and eigenvector\n---\n")
cat(mat %*% evectors[,1], "\n---\n")
cat("eigenvalue and eigenvector\n---\n")
cat(evalues[1] * evectors[,1])

Matrix and eigenvector
---
-3.029457 -6.976159
---
eigenvalue and eigenvector
---
-3.029457 -6.976159

In [4]:
# Verify multiplication for the second eigvalue-eigenvector pair
# matrix x eigenvector = eigenvalue x eigenvector
cat("Matrix and eigenvector\n---\n")
cat(mat %*% evectors[,2], "\n---\n")
cat("eigenvalue and eigenvector\n---\n")
cat(evalues[2] * evectors[,2])

Matrix and eigenvector
---
-0.2401773 0.3128972
---
eigenvalue and eigenvector
---
-0.2401773 0.3128972

In [7]:
# Trace
sum(diag(mat)) == sum(evalues)

[1] TRUE

# 2. Singular value decomposition

In [8]:
mat_svd <- svd(x = mat)
mat_svd

$d
[1] 8.5952416 0.3490303

$u
           [,1]       [,2]
[1,] -0.4178568 -0.9085129
[2,] -0.9085129  0.4178568

$v
           [,1]       [,2]
[1,] -0.7800418 -0.6257274
[2,] -0.6257274  0.7800418

In [9]:
sessionInfo()

R version 4.5.3 (2026-03-11)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] digest_0.6.39     IRdisplay_1.1     base64enc_0.1-6   fastmap_1.2.0
 [5] glue_1.8.0        htmltools_0.5.9   repr_1.1.7        lifecycle_1.0.5
 [9] cli_3.6.5         vctrs_0.7.1       textshaping_1.0.5 pbdZMQ_0.3-14
[13] systemfonts_1.3.2 compiler_4.5.3    tools_4.5.3       ragg_1.5.1
[17] evaluate_1.0.5    pillar_1.11.1     rlang_1.1.7       jsonlite_2.0.0
[21] crayon_1.5.3      IRkernel_1.3.2    uuid_1.2-2